### ISSUE TITLE
[Feature] Product 도메인의 테스트 코드 작성

### ISSUE THREAD

**Issue by POKUDING** [GaePpaDev/GaePpa-BackEnd-DEV#25]
## 📜 Description
Product 도메인의 테스트 코드를 작성합니다.

컨트롤러와 서비스의 테스트 코드를 작성하여 기능 작동의 안정성을 유지하고 CI에 적용 할 수 있습니다.
적용하는 범위는 아래와 같습니다.
- ProductCategory
- Product
- ProductOptionCategory
- ProductOption

## 🌈 Success criteria
- 모든 컨트롤러와 서비스단의 테스트가 생성됩니다.
- 최대한 예외처리에 대한 테스트도 작성합니다.

## 👷 To-do
- [ ] 컨트롤러의 테스트 작성
- [ ] 서비스의 테스트 작성
- [ ] Validation의 테스트 작성

##  🔗Related issues

Related to: #18
