### ISSUE TITLE
[Feature] AI를 활용한 상품 설명 어시스트 기능 개발

### ISSUE THREAD

**Issue by POKUDING** [GaePpaDev/GaePpa-BackEnd-DEV#31]
## 📜 Description
- AI의 도움을 받아서 상품의 설명을 받을 수 있는 기능입니다.
- AI의 기본적임 프롬포트 템플릿과 유저가 입력한 프롬포트를 DB에 저장합니다.

## 🌈 Success criteria
- AI의 도움을 받아서 상품의 설명을 받을 수 있는 API 개발

## 👷 To-do
- [ ] SpringAI 와 구글 AI 레퍼런스 체크
- [ ] 구글 AI를 연동하여 요청과 응답 테스트
- [ ] 프롬포트 템플릿 작성 및 AI 응답 테스트
- [ ] 유저의 입력값과 프롬포트 템플릿을 결합하여 AI 요청
- [ ]  AI의 요청과 응답값을 DB에 저장 로직 개발
- [ ] PostMan을 이용한 테스트

##  🔗Related issues

Related to: #이슈번호
