### ISSUE TITLE
[Feature] Global Exception Handler dev

### ISSUE THREAD

**Issue by POKUDING** [GaePpaDev/GaePpa-BackEnd-DEV#4]
## 📜 Description
전역 예외 핸들러를 개발합니다.

## 🌈 Success criteria
전역 예외 핸들러를 작성하고 모든 예외 처리가 전역 핸들러로 관리되야 합니다.

## 👷 To-do
- [ ] 전역 예외 핸들러 개발
- [ ] ENUM 으로 예외 상황 관리
- [ ] 예외에 따른 log를 처리
- [ ] 모든 예외가 핸들러로 처리 되는지 테스트
